//
//  Constants.swift
//  TouchymPOS
//
//  Created by user115796 on 3/2/16.
//  Copyright © 2016 aljaber. All rights reserved.
//

import UIKit

open class Constants: NSObject {
    
    open static let SEARCH_REQUEST                : String = "searchReqeust"
    open static let FILTTER_REQEUST               : String = "filtterReqeust"
    open static let ERROR_RESPONSE                : String = "errorResponse"
    
    open static let ADMIN_COMPANY_KEY             : String = "COMPANY_CODE"
    open static let ADMIN_COUNTER_KEY             : String = "COUNTER_CODE"
    open static let ADMIN_LOCATION_key            : String = "LOCATION_CODE"
    open static let ADMIN_URL_KEY                 : String = "URL"
    open static let ADMIN_SETTING_FILE_NAME       : String = "AdminSetting.plist"
    open static let ADMIN_IS_CU_SAVED_DATA        : String = "IS_CUSTOMER_SAVED_DATA"
    
    open static let CU_SEARCH_BY_PHONE_NO         : String = "searchByPhoneNo"
    open static let SEARCH_NO_RESULT              : String = "noResult"
    open static let CU_SEARCH_BY_RX_CONTACT_LENSE : String = "searchByRxContactLense"
    open static let CU_SEARCH_BY_HISTORY          : String = "searchByHistory"
    open static let CU_SEARCH_BY_RX_GLASSES       : String = "searchByRxGlasses"
    open static let CU_SEARCH_BY_SLIT_K_READING   : String = "searchBySlitKReading"
    open static let CU_SEARCH_BY_TRAIL            : String = "searchByTrail"
    open static let CU_SAVE_CUSTOMER_INFO         : String = "saveCustomerInfo"
    open static let CU_SAVE_CUSTOMER_OBJ_NAME     : String = "patientObj"
    open static let CU_SEARCH_BY_INVOICE      : String = "searchByInvoice"
    open static let CU_SEARCH_BY_SALES_ORDER     : String = "searchBySalesOrder"
    open static let LOCN_WORKORDER_NOTIFICATION     : String = "getLocationWorkOrderNotification"
    
    
    open static let LOGGED_USER_NAME              : String = "loggedUserName"
    open static let TRUE                          : String = "true"
    open static let FALSE                         : String = "false"
    open static let CU_SEARCH_BY_HISTORY_INVOICE  : String = "searchCustomerHistoryInvoice"
    open static let CU_SEARCH_BY_HISTORY_SALES_ORDER: String = "searchCustomerHistorySalesOrder"
    open static let SAVE_RX_GLASSES_INFO         : String = "saveRxGlassesInfo"
    open static let SAVE_RX_CONTACT_LENS_INFO         : String = "saveRxContactLenseInfo"
    open static let SAVE_RX_TRAIL_INFO         : String = "saveRxTrailInfo"
    open static let SAVE_RX_SLIT_K_READIND_INFO         : String = "saveRxSlitKReadingInfo"
    
    open static let SAVE_RX_CONTACT_LENSE_INFO_RESULT = "rxContactLensObj"
    open static let SAVE_WORK_ORDER_INFO = "workOrderObj"
    open static let SAVE_WORK_ORDER = "saveWorkOrder"
    open static let FILTER_WORK_ORDER_STATUS = "filterWorkOrder"
    open static let FIND_WORK_ORDER_STATUSES = "workOrderStatuses"
    open static let FIND_WORK_ORDER_STATUS_CHECK = "workOrderStatusCheck"
    
    open static let SAVE_REPAIR_ORDER = "saveRepairOrder"
    open static let SAVE_REPAIR_ORDER_INFO = "repairOrderObj"
    open static let FILTER_REPAIR_ORDER_STATUS = "filterRepairOrder"
    open static let FIND_REPAIR_ORDER_STATUSES = "repairOrderStatuses"
    open static let FIND_REPAIR_ORDER_STATUS_CHECK = "repairOrderStatusCheck"
    
    open static let VIEWER_SETTING_PAGE_VIEWER : String = "SettingPageViewer"
    open static let VIEWER_ADD_EDIT_CUSTOMER_VIEWER : String = "AddEditCustomerViewer"
    open static let VIEWER_CUSTOMER_DETAILED_INFO_VIEWER : String = "CustomerDetailedInfoViewer"
    open static let VIEWER_RX_GLASSES_DETAILED_VIEWER : String = "RxGlassDetailedViewer"
    open static let VIEWER_RX_CONTACT_LENSE_DETAILED_VIEWER : String = "RxContactLenseDetailedViewer"
    open static let VIEWER_RX_TRAIL_DETAILED_VIEWER : String = "RxTrailDetailedViewer"
    open static let VIEWER_RX_SLIT_K_DETAILED_VIEWER : String = "RxSlitKReadingDetailedViewer"
    open static let VIEWER_WORK_ORDER_ADD_EDIT_VIEWER : String = "WorkOrderAddEditView"
    open static let VIEWER_WORK_ORDER_STATUS_HOME : String = "WorkOrderStatusHome"
    open static let VIEWER_WORK_ORDER_DETAILS : String = "WorkOrderDetails"
    open static let VIEWER_REPAIR_ORDER_ADD_EDIT_VIEWER : String = "RepairOrderAddEditView"
    open static let VIEWER_REPAIR_ORDER_STATUS_HOME : String = "RepairOrderStatusHome"
    open static let VIEWER_REPAIR_ORDER_DETAILS : String = "RepairOrderDetails"
    
    open static let LIST_VIEW_SEARCH_COMPANY_CODE : String = "SEARCH_ALL_COMPANY_CODE"
    open static let LIST_VIEW_SEARCH_LOCATION_CODE : String = "SEARCH_ALL_LOCATION_CODE"
    open static let LIST_VIEW_SEARCH_COUNTER_CODE : String = "SEARCH_ALL_COUNTER_CODE"
    open static let LIST_VIEW_SEARCH_WORKORDER_STATUS : String = "SEARCH_ALL_WORKORDER_STATUS_CODE"
    open static let LIST_VIEW_SEARCH_COUNTRY : String = "SEARCH_ALL_COUNTRY_CODE"
    open static let LIST_VIEW_SEARCH_SALES_MAN : String = "SEARCH_ALL_SALES_MAN"
    open static let LIST_VIEW_SEARCH_REQUEST : String = "SEARCH_ALL_REQUEST"
    open static let LIST_VIEW_SEARCH_STOCK_GROUP : String = "SEARCH_ALL_STOCK_GROUP"
    open static let LIST_VIEW_SEARCH_STOCK_FROM_ITEM : String = "SEARCH_ALL_STOCK_FROM_ITEM"
    open static let LIST_VIEW_SEARCH_STOCK_TO_ITEM : String = "SEARCH_ALL_STOCK_TO_ITEM"
    open static let LIST_VIEW_SEARCH_STOCK_SUB_GROUP : String = "SEARCH_ALL_STOCK_SUB_GROUP"
    open static let LIST_VIEW_SHOW_DROP_DOWN_OPTIONS : String = "SHOW_DROP_DOWN_OPTIONS"
    open static let LIST_VIEW_SHOW_INVOICE_ITEMS : String = "SHOW_INVOICE_ITEMS"
    open static let LIST_VIEW_SEARCH_REPAIRORDER_STATUS : String = "SEARCH_ALL_REPAIRORDER_STATUS_CODE"
    
    
    
    open static let LOV_CODE  = "LOV_CODE"
    open static let LOV_NAME  = "LOV_NAME"
    open static let LOV_VALUE = "LOV_VALUE"
    
    open static let TAG_ADMIN_SETTING_COMPANY_CODE : Int = 1
    open static let TAG_ADMIN_SETTING_LOCATION_CODE : Int = 2
    open static let TAG_ADMIN_SETTING_COUNTER_CODE : Int = 3
    
    open static let OPERATION_TYPE_ADD = "ADD"
    open static let OPERATION_TYPE_EDIT = "EDIT"
    open static let OPERATION_TYPE_DELETE = "DELETE"
    open static let OPERATION_TYPE = "OP_TYPE"
    open static let OPERATION_TYPE_VIEW = "VIEW"
    
    open static let UserName = "UserName"
    open static let Password = "Password"
    open static let MACID = "MACID"
    open static let CompCode = "CompCode"
    open static let DeviceName = "DEVICE_NAME"
    open static let DeviceModel = "DEVICE_MODEL"
    
    /*Login Reqeust Response Constants start*/
    open static let LOGIN_STATUS  = "Status"
    open static let LOGIN_MESSAGE = "Message"
    open static let COMP_CODE = "COMP_CODE"
    open static let COMP_NAME = "COMP_NAME"
    open static let LOCN_CODE = "LOCN_CODE"
    open static let LOCN_NAME = "LOCN_NAME"
    open static let COUNT_CODE = "COUNT_CODE"
    open static let COUNT_NAME = "COUNT_NAME"
    open static let COUNT_SETUP = "COUNT_SETUP"
    open static let ADV_PAY_CODE = "ADV_PAY_CODE"
    open static let CUST_CODE = "CUST_CODE"
    open static let LINE_DISP_WL_1 = "LINE_DISP_WL_1"
    open static let PAY_CODE = "PAY_CODE"
    open static let PL_CODE = "PL_CODE"
    open static let LOCN_SETUP = "LOCN_SETUP"
    open static let AUTO_CALC_DISC_YN = "AUTO_CALC_DISC_YN"
    open static let A_BK_DATE = "A_BK_DATE"
    open static let A_BONUS_DISCOUNT = "A_BONUS_DISCOUNT"
    open static let BARCODE_TYPE = "BARCODE_TYPE"
    open static let BUSINESS_ACROSS_DAYS = "BUSINESS_ACROSS_DAYS"
    open static let BUSINESS_HOUR_FROM = "BUSINESS_HOUR_FROM"
    open static let BUSINESS_HOUR_TO = "BUSINESS_HOUR_TO"
    open static let CREDIT_CONTROL_CUSTOMER = "CREDIT_CONTROL_CUSTOMER"
    open static let DISC_TAX_YN = "DISC_TAX_YN"
    open static let EXP_TAX_YN = "EXP_TAX_YN"
    open static let NOT_CC_RC_CUST = "NOT_CC_RC_CUST"
    open static let ORD_LEV_DISC_INC = "ORD_LEV_DISC_INC"
    open static let QUERY_LOCATION = "QUERY_LOCATION"
    open static let REGULAR_CUSTOMER = "REGULAR_CUSTOMER"
    open static let SHIFT_ALERT_BEFORE = "SHIFT_ALERT_BEFORE"
    open static let SHIFT_ALERT_INTERVAL = "SHIFT_ALERT_INTERVAL"
    open static let VAT_REQUIRED_YN = "VAT_REQUIRED_YN"
    /*Login Request Response Constatns end*/
    
    /**/
    open static let SUCCESS = "Success"
    open static let MSG_SUCCESS = "User is validated successfully"
    open static let MSG_INVALID_UESR_PASS = "User and Password is not valid"
    open static let MSG_INVALID_DEVICE = "Device is not valid! Please contanct admin team..."
    open static let MSG_INVALID_COMPANY = "Company is not valid"
    open static let FAILED = "Failed"
    /**/
    
    
    /*Patient Master Constants */
    open static let PM_ADDRESS_1 : String = "PM_ADDRESS_1"
    open static let PM_ADDRESS_2 : String = "PM_ADDRESS_2"
    open static let PM_ADDRESS_3 : String = "PM_ADDRESS_3"
    open static let PM_ADDRESS_4 : String = "PM_ADDRESS_4"
    open static let PM_ADDRESS_5 : String = "PM_ADDRESS_5"
    open static let PM_CITY : String = "PM_CITY"
    open static let PM_COMPANY : String = "PM_COMPANY"
    open static let PM_COMP_CODE : String = "PM_COMP_CODE"
    open static let PM_COUNTER_CODE : String = "PM_COUNTER_CODE"
    open static let PM_COUNTRY : String = "PM_COUNTRY"
    open static let PM_CR_DT : String = "PM_CR_DT"
    open static let PM_CR_UID : String = "PM_CR_UID"
    open static let PM_CUST_CODE : String = "PM_CUST_CODE"
    open static let PM_CUST_NAME : String = "PM_CUST_NAME"
    open static let PM_CUST_NO : String = "PM_CUST_NO"
    open static let PM_DOB : String = "PM_DOB"
    open static let PM_EMAIL : String = "PM_EMAIL"
    open static let PM_FRZ_FLAG_NUM : String = "PM_FRZ_FLAG_NUM"
    open static let PM_GENDER : String = "PM_GENDER"
    open static let PM_LOCN_CODE : String = "PM_LOCN_CODE"
    open static let PM_NATIONALITY : String = "PM_NATIONALITY"
    open static let PM_NOTES : String = "PM_NOTES"
    open static let PM_OCCUPATION : String = "PM_OCCUPATION"
    open static let PM_PATIENT_NAME : String = "PM_PATIENT_NAME"
    open static let PM_PD_ORDER_DT : String = "PM_PD_ORDER_DT"
    open static let PM_PD_ORDER_NO : String = "PM_PD_ORDER_NO"
    open static let PM_PD_SYS_ID : String = "PM_PD_SYS_ID"
    open static let PM_REGION : String = "PM_REGION"
    open static let PM_REMARKS : String = "PM_REMARKS"
    open static let PM_SM_CODE : String = "PM_SM_CODE"
    open static let PM_SYS_ID :  String = "PM_SYS_ID"
    open static let PM_TEL_MOB : String = "PM_TEL_MOB"
    open static let PM_TEL_OFF : String = "PM_TEL_OFF"
    open static let PM_TEL_RES : String = "PM_TEL_RES"
    open static let PM_UPD_DT : String = "PM_UPD_DT"
    open static let PM_UPD_UID : String = "PM_UPD_UID"
    open static let PM_ZIPCODE : String = "PM_ZIPCODE"
    open static let PM_FLEX_20 : String = "PM_FLEX_20"
    /*Patient Master End*/
    
    /*Rx Contact Lense Constants Start */
    
    open static let PRXCL_COMP_CODE="PRXCL_COMP_CODE"
    open static let PRXCL_COUNTER_CODE="PRXCL_COUNTER_CODE"
    open static let PRXCL_CR_DT="PRXCL_CR_DT"
    open static let PRXCL_CR_UID="PRXCL_CR_UID"
    open static let PRXCL_DATE="PRXCL_DATE"
    open static let PRXCL_FLEX_01="PRXCL_FLEX_01"
    open static let PRXCL_FLEX_02="PRXCL_FLEX_02"
    open static let PRXCL_FLEX_03="PRXCL_FLEX_03"
    open static let PRXCL_FLEX_04="PRXCL_FLEX_04"
    open static let PRXCL_FLEX_05="PRXCL_FLEX_05"
    open static let PRXCL_FLEX_06="PRXCL_FLEX_06"
    open static let PRXCL_FLEX_07="PRXCL_FLEX_07"
    open static let PRXCL_FLEX_08="PRXCL_FLEX_08"
    open static let PRXCL_FLEX_09="PRXCL_FLEX_09"
    open static let PRXCL_FLEX_10="PRXCL_FLEX_10"
    open static let PRXCL_FRZ_FLAG_NUM="PRXCL_FRZ_FLAG_NUM"
    open static let PRXCL_LOCN_CODE="PRXCL_LOCN_CODE"
    open static let PRXCL_L_ADD="PRXCL_L_ADD"
    open static let PRXCL_L_BC="PRXCL_L_BC"
    open static let PRXCL_L_BRAND="PRXCL_L_BRAND"
    open static let PRXCL_L_DIA="PRXCL_L_DIA"
    open static let PRXCL_L_D_AXIS="PRXCL_L_D_AXIS"
    open static let PRXCL_L_D_CYL="PRXCL_L_D_CYL"
    open static let PRXCL_L_D_SPH="PRXCL_L_D_SPH"
    open static let PRXCL_L_D_VISION="PRXCL_L_D_VISION"
    open static let PRXCL_L_II_BCOR="PRXCL_L_II_BCOR"
    open static let PRXCL_L_II_DIA="PRXCL_L_II_DIA"
    open static let PRXCL_L_II_POWER="PRXCL_L_II_POWER"
    open static let PRXCL_L_I_BCOR="PRXCL_L_I_BCOR"
    open static let PRXCL_L_I_DIA="PRXCL_L_I_DIA"
    open static let PRXCL_L_I_POWER="PRXCL_L_I_POWER"
    open static let PRXCL_L_N_AXIS="PRXCL_L_N_AXIS"
    open static let PRXCL_L_N_CYL="PRXCL_L_N_CYL"
    open static let PRXCL_L_N_SPH="PRXCL_L_N_SPH"
    open static let PRXCL_L_N_VISION="PRXCL_L_N_VISION"
    open static let PRXCL_PM_SYS_ID="PRXCL_PM_SYS_ID"
    open static let PRXCL_REMARK="PRXCL_REMARK"
    open static let PRXCL_R_ADD="PRXCL_R_ADD"
    open static let PRXCL_R_BC="PRXCL_R_BC"
    open static let PRXCL_R_BRAND="PRXCL_R_BRAND"
    open static let PRXCL_R_DIA="PRXCL_R_DIA"
    open static let PRXCL_R_D_AXIS="PRXCL_R_D_AXIS"
    open static let PRXCL_R_D_CYL="PRXCL_R_D_CYL"
    open static let PRXCL_R_D_SPH="PRXCL_R_D_SPH"
    open static let PRXCL_R_D_VISION="PRXCL_R_D_VISION"
    open static let PRXCL_R_II_BCOR="PRXCL_R_II_BCOR"
    open static let PRXCL_R_II_DIA="PRXCL_R_II_DIA"
    open static let PRXCL_R_II_POWER="PRXCL_R_II_POWER"
    open static let PRXCL_R_I_BCOR="PRXCL_R_I_BCOR"
    open static let PRXCL_R_I_DIA="PRXCL_R_I_DIA"
    open static let PRXCL_R_I_POWER="PRXCL_R_I_POWER"
    open static let PRXCL_R_N_AXIS="PRXCL_R_N_AXIS"
    open static let PRXCL_R_N_CYL="PRXCL_R_N_CYL"
    open static let PRXCL_R_N_SPH="PRXCL_R_N_SPH"
    open static let PRXCL_R_N_VISION="PRXCL_R_N_VISION"
    open static let PRXCL_SM_CODE="PRXCL_SM_CODE"
    open static let PRXCL_SYS_ID="PRXCL_SYS_ID"
    open static let PRXCL_UPD_DT="PRXCL_UPD_DT"
    open static let PRXCL_UPD_UID="PRXCL_UPD_UID"
    /*Rx Contact Lense End*/
    
    /*Patiend History Constants Start*/
    open static let PV_COMP_CODE = "PV_COMP_CODE"
    open static let PV_DATE = "PV_DATE"
    open static let PV_InvoiceNo = "PV_InvoiceNo"
    open static let PV_LOCN_CODE = "PV_LOCN_CODE"
    open static let PV_SalesOrderNo = "PV_SalesOrderNo"
    /*Patiend History End*/
    
    /*RxGlass Details*/
    open static let PRXG_COMP_CODE = "PRXG_COMP_CODE"
    open static let PRXG_COUNTER_CODE = "PRXG_COUNTER_CODE"
    open static let PRXG_CR_DT = "PRXG_CR_DT"
    open static let PRXG_CR_UID = "PRXG_CR_UID"
    open static let PRXG_DATE = "PRXG_DATE"
    open static let PRXG_FRZ_FLAG_NUM = "PRXG_FRZ_FLAG_NUM"
    open static let PRXG_LOCN_CODE = "PRXG_LOCN_CODE"
    open static let PRXG_L_ADD = "PRXG_L_ADD"
    open static let PRXG_L_D_AXIS = "PRXG_L_D_AXIS"
    open static let PRXG_L_D_CYL = "PRXG_L_D_CYL"
    open static let PRXG_L_D_SPH = "PRXG_L_D_SPH"
    open static let PRXG_L_D_VISION = "PRXG_L_D_VISION"
    open static let PRXG_L_N_AXIS = "PRXG_L_N_AXIS"
    open static let PRXG_L_N_CYL = "PRXG_L_N_CYL"
    open static let PRXG_L_N_SPH = "PRXG_L_N_SPH"
    open static let PRXG_L_N_VISION = "PRXG_L_N_VISION"
    open static let PRXG_L_PD = "PRXG_L_PD"
    open static let PRXG_L_PRIZM = "PRXG_L_PRIZM"
    open static let PRXG_PM_SYS_ID = "PRXG_PM_SYS_ID"
    open static let PRXG_REMARK = "PRXG_REMARK"
    open static let PRXG_R_ADD = "PRXG_R_ADD"
    open static let PRXG_R_D_AXIS = "PRXG_R_D_AXIS"
    open static let PRXG_R_D_CYL = "PRXG_R_D_CYL"
    open static let PRXG_R_D_SPH = "PRXG_R_D_SPH"
    open static let PRXG_R_D_VISION = "PRXG_R_D_VISION"
    open static let PRXG_R_N_AXIS = "PRXG_R_N_AXIS"
    open static let PRXG_R_N_CYL = "PRXG_R_N_CYL"
    open static let PRXG_R_N_SPH = "PRXG_R_N_SPH"
    open static let PRXG_R_N_VISION = "PRXG_R_N_VISION"
    open static let PRXG_R_PD = "PRXG_R_PD"
    open static let PRXG_R_PRIZM = "PRXG_R_PRIZM"
    open static let PRXG_SM_CODE = "PRXG_SM_CODE"
    open static let PRXG_SYS_ID = "PRXG_SYS_ID"
    open static let PRXG_UPD_DT = "PRXG_UPD_DT"
    open static let PRXG_UPD_UID = "PRXG_UPD_UID"
    /**/
    /**/
    open static let PRXTD_COMP_CODE = "PRXTD_COMP_CODE"
    open static let PRXTD_COUNTER_CODE = "PRXTD_COUNTER_CODE"
    open static let PRXTD_CR_DT = "PRXTD_CR_DT"
    open static let PRXTD_CR_UID = "PRXTD_CR_UID"
    open static let PRXTD_DATE = "PRXTD_DATE"
    open static let PRXTD_FRZ_FLAG_NUM = "PRXTD_FRZ_FLAG_NUM"
    open static let PRXTD_LENS_USED_LE = "PRXTD_LENS_USED_LE"
    open static let PRXTD_LENS_USED_LE_ADD = "PRXTD_LENS_USED_LE_ADD"
    open static let PRXTD_LENS_USED_LE_VIA = "PRXTD_LENS_USED_LE_VIA"
    open static let PRXTD_LENS_USED_RE = "PRXTD_LENS_USED_RE"
    open static let PRXTD_LENS_USED_RE_ADD = "PRXTD_LENS_USED_RE_ADD"
    open static let PRXTD_LENS_USED_RE_VIA = "PRXTD_LENS_USED_RE_VIA"
    open static let PRXTD_LE_REMARKS = "PRXTD_LE_REMARKS"
    open static let PRXTD_LOCN_CODE = "PRXTD_LOCN_CODE"
    open static let PRXTD_PM_SYS_ID = "PRXTD_PM_SYS_ID"
    open static let PRXTD_REMARK = "PRXTD_REMARK"
    open static let PRXTD_RE_REMARKS = "PRXTD_RE_REMARKS"
    open static let PRXTD_SM_CODE = "PRXTD_SM_CODE"
    open static let PRXTD_SYS_ID = "PRXTD_SYS_ID"
    open static let PRXTD_UPD_DT = "PRXTD_UPD_DT"
    open static let PRXTD_UPD_UID = "PRXTD_UPD_UID"
    /**/
    
    /*Slit K Reading*/
    open static let PRXSKR_COMP_CODE = "PRXSKR_COMP_CODE"
    open static let PRXSKR_COUNTER_CODE = "PRXSKR_COUNTER_CODE"
    open static let PRXSKR_CR_DT = "PRXSKR_CR_DT"
    open static let PRXSKR_CR_UID = "PRXSKR_CR_UID"
    open static let PRXSKR_DATE = "PRXSKR_DATE"
    open static let PRXSKR_FLEX_01 = "PRXSKR_FLEX_01"
    open static let PRXSKR_FLEX_02 = "PRXSKR_FLEX_02"
    open static let PRXSKR_FLEX_03 = "PRXSKR_FLEX_03"
    open static let PRXSKR_FLEX_04 = "PRXSKR_FLEX_04"
    open static let PRXSKR_FLEX_05 = "PRXSKR_FLEX_05"
    open static let PRXSKR_FLEX_06 = "PRXSKR_FLEX_06"
    open static let PRXSKR_FLEX_07 = "PRXSKR_FLEX_07"
    open static let PRXSKR_FLEX_08 = "PRXSKR_FLEX_08"
    open static let PRXSKR_FLEX_09 = "PRXSKR_FLEX_09"
    open static let PRXSKR_FLEX_10 = "PRXSKR_FLEX_10"
    open static let PRXSKR_FRZ_FLAG_NUM = "PRXSKR_FRZ_FLAG_NUM"
    open static let PRXSKR_K_LE_HORIZONTAL  = "PRXSKR_K_LE_HORIZONTAL"
    open static let PRXSKR_K_LE_VERTICAL = "PRXSKR_K_LE_VERTICAL"
    open static let PRXSKR_K_RE_HORIZONTAL = "PRXSKR_K_RE_HORIZONTAL"
    open static let PRXSKR_K_RE_VERTICAL = "PRXSKR_K_RE_VERTICAL"
    open static let PRXSKR_LOCN_CODE = "PRXSKR_LOCN_CODE"
    open static let PRXSKR_PM_SYS_ID = "PRXSKR_PM_SYS_ID"
    open static let PRXSKR_REMARK = "PRXSKR_REMARK"
    open static let PRXSKR_SLIT_LE = "PRXSKR_SLIT_LE"
    open static let PRXSKR_SLIT_LRIS = "PRXSKR_SLIT_LRIS"
    open static let PRXSKR_SLIT_RE = "PRXSKR_SLIT_RE"
    open static let PRXSKR_SM_CODE = "PRXSKR_SM_CODE"
    open static let PRXSKR_SYS_ID = "PRXSKR_SYS_ID"
    open static let PRXSKR_UPD_DT = "PRXSKR_UPD_DT"
    open static let PRXSKR_UPD_UID = "PRXSKR_UPD_UID"
    /**/
    
    open static let TRANS_NO = "TRANS_NO"
    open static let TRANS_DATE = "TRANS_DATE"
    open static let TRANS_LOCN = "TRANS_LOCN"
    open static let TRANS_SALESMAN = "TRANS_SALESMAN"
    open static let TRANS_PATIENT_NO = "TRANS_PATIENT_NO"
    open static let TRANS_PATIENT_NAME = "TRANS_PATIENT_NAME"
    open static let TRANS_DISC = "TRANS_DISC"
    open static let TRANS_EXP = "TRANS_EXP"
    open static let TRANS_SUB_TOTAL = "TRANS_SUB_TOTAL"
    open static let TRANS_GROSS_TOTAL = "TRANS_GROSS_TOTAL"
    open static let TRANS_ITEMS = "TRANS_ITEMS"
    open static let ITEM_CODE = "ITEM_CODE"
    open static let ITEM_NAME = "ITEM_NAME"
    open static let ITEM_UOM = "ITEM_UOM"
    open static let ITEM_RATE = "ITEM_RATE"
    open static let ITEM_DISCOUNT = "ITEM_DISCOUNT"
    open static let ITEM_QTY = "ITEM_QTY"
    open static let ITEM_AMT = "ITEM_AMT"

    open static let ITEM_DESC = "ITEM_DESC"
    open static let ITEM_BAR_CODE = "ITEM_BAR_CODE"
    open static let ITEM_GRADE_CODE = "ITEM_GRADE_CODE"
    open static let ITEM_PRICE1 = "ITEM_PRICE1"
    open static let ITEM_PRICE2 = "ITEM_PRICE2"
    open static let ITEM_STOCK = "ITEM_STOCK"
    open static let ITEM_LOCATION = "ITEM_LOCATION"
    open static let ITEM_PL_CODE = "ITEM_PL_CODE"
    
    
    open static let FIELD_SHOULD_NOT_EDIT = 1
    open static let FIELD_SHOULD_EDIT_SHOULD_NOT_MOVE = 2
    open static let FIELD_SHOULD_EDIT_SHOULD_MOVE = 3
    
    open static let MAIN_GROUP = "MAIN_GROUP"
    open static let SUB_GROUP = "SUB_GROUP"
    open static let FROM_ITEM = "FROM_ITEM"
    open static let TO_ITEM = "TO_ITEM"
    
    open static let VIEWER_STOCK_QUERY_DETAULS : String = "StockQueryHomePageViewer"
    open static let SEARCH_STOCK_QUERY_ITEM : String = "SearchStockQueryIteam"
    
    open static let STOCK_ITEM_GRADE_CODE = "ITEM_GRADE_CODE"
    open static let STOCK_ITEM_PRICE1 = "ITEM_PRICE1"
    open static let STOCK_ITEM_BAR_CODE = "ITEM_BAR_CODE"
    open static let STOCK_ITEM_STOCK = "ITEM_STOCK"
    open static let STOCK_ITEM_DESC = "ITEM_DESC"
    open static let STOCK_ITEM_CODE = "ITEM_CODE"
    open static let STOCK_ITEM_PRICE2 = "ITEM_PRICE2"
    
    open static let RX_GLASS = "RXGlass"
    open static let RX_CONTACT_LENS = "RXContactLens"
    open static let RX_SLITK_READING = "SlitKReading"
    open static let TRAIL = "Trial"
    
    open static let SEND_MAIL_POST_REQUEST = "SendMail"
    open static let EMAIL_TYPE = "EmailType"
    open static let TABLE_SYS_ID = "TableSysId"
    open static let EMAIL_ID = "EmailID"
    
    /* To handle dynamic controls in Work Order & Job Order  */
    open static let SEARCH_STOCK_QUERY_LOCATION_WISE_ITEM : String = "SearchStockQueryLocationWiseIteam"
    
    open static let DYN_VISIT_TYPE = "DYN_VISIT_TYPE"
    open static let DYN_CTLS_NUMBER = "DYN_CTLS_NUMBER"
    open static let DYN_CTLS = "DYN_CTLS"
    
    open static let DYNAMIC_CONTROL_TYPE_WISE : String = "DynamicControlTypeWise"
    
    open static let CTL_PARENT = "CTL_PARENT"
    open static let CTL_GROUP = "CTL_GROUP"
    open static let CTL_GROUP_NAME = "CTL_GROUP_NAME"
    open static let CTL_TYPE = "CTL_TYPE"
    open static let CTL_NAME = "CTL_NAME"
    open static let CTL_LABEL_TEXT = "CTL_LABEL_TEXT"
    open static let CTL_DATATYPE = "CTL_DATATYPE"
    open static let CTL_MIN_CHAR = "CTL_MIN_CHAR"
    open static let CTL_MAX_CHAR = "CTL_MAX_CHAR"
    open static let CTL_MANDATORY = "CTL_MANDATORY"
    open static let CTL_VALUES = "CTL_VALUES"
    open static let CTL_MAPPED_FIELD = "CTL_MAPPED_FIELD"
    open static let CTL_IMAGE_SELECT = "CTL_IMAGE_SELECT"
    open static let CTL_GROUP_FIELDS = "CTL_GROUP_FIELDS"
    
    open static let CTL_SWITCH_TYPE = "Switch"
    open static let CTL_TEXTAREA_TYPE = "TextArea"
    open static let CTL_TEXTFIELD_TYPE = "TextField"
    open static let CTL_DROPDOWN = "Select"
    open static let CTL_RIGHTLEFT_CHECKBOX = "RightLeftCheckbox"
    
    /* TPOS WORK ORDER DETAIL  */
    open static let TPOSWOD_SYS_ID    = "TPOSWOD_SYS_ID"
    open static let TPOSWOD_HEAD_SYS_ID  = "TPOSWOD_HEAD_SYS_ID"
    open static let TPOSWOD_FLEX_1     = "TPOSWOD_FLEX_1"
    open static let TPOSWOD_FLEX_2     = "TPOSWOD_FLEX_2"
    open static let TPOSWOD_FLEX_3     = "TPOSWOD_FLEX_3"
    open static let TPOSWOD_FLEX_4     = "TPOSWOD_FLEX_4"
    open static let TPOSWOD_FLEX_5     = "TPOSWOD_FLEX_5"
    open static let TPOSWOD_FLEX_6     = "TPOSWOD_FLEX_6"
    open static let TPOSWOD_FLEX_7     = "TPOSWOD_FLEX_7"
    open static let TPOSWOD_FLEX_8     = "TPOSWOD_FLEX_8"
    open static let TPOSWOD_FLEX_9     = "TPOSWOD_FLEX_9"
    open static let TPOSWOD_FLEX_10    = "TPOSWOD_FLEX_10"
    open static let TPOSWOD_FLEX_11    = "TPOSWOD_FLEX_11"
    open static let TPOSWOD_FLEX_12    = "TPOSWOD_FLEX_12"
    open static let TPOSWOD_FLEX_13    = "TPOSWOD_FLEX_13"
    open static let TPOSWOD_FLEX_14    = "TPOSWOD_FLEX_14"
    open static let TPOSWOD_FLEX_15    = "TPOSWOD_FLEX_15"
    open static let TPOSWOD_FLEX_16    = "TPOSWOD_FLEX_16"
    open static let TPOSWOD_FLEX_17    = "TPOSWOD_FLEX_17"
    open static let TPOSWOD_FLEX_18    = "TPOSWOD_FLEX_18"
    open static let TPOSWOD_FLEX_19    = "TPOSWOD_FLEX_19"
    open static let TPOSWOD_FLEX_20    = "TPOSWOD_FLEX_20"
    open static let TPOSWOD_FLEX_21    = "TPOSWOD_FLEX_21"
    open static let TPOSWOD_FLEX_22    = "TPOSWOD_FLEX_22"
    open static let TPOSWOD_FLEX_23    = "TPOSWOD_FLEX_23"
    open static let TPOSWOD_FLEX_24    = "TPOSWOD_FLEX_24"
    open static let TPOSWOD_FLEX_25    = "TPOSWOD_FLEX_25"
    open static let TPOSWOD_FLEX_26    = "TPOSWOD_FLEX_26"
    open static let TPOSWOD_FLEX_27    = "TPOSWOD_FLEX_27"
    open static let TPOSWOD_FLEX_28    = "TPOSWOD_FLEX_28"
    open static let TPOSWOD_FLEX_29    = "TPOSWOD_FLEX_29"
    open static let TPOSWOD_FLEX_30    = "TPOSWOD_FLEX_30"
    open static let TPOSWOD_FLEX_31    = "TPOSWOD_FLEX_31"
    open static let TPOSWOD_FLEX_32    = "TPOSWOD_FLEX_32"
    open static let TPOSWOD_FLEX_33    = "TPOSWOD_FLEX_33"
    open static let TPOSWOD_FLEX_34    = "TPOSWOD_FLEX_34"
    open static let TPOSWOD_FLEX_35    = "TPOSWOD_FLEX_35"
    open static let TPOSWOD_FLEX_36    = "TPOSWOD_FLEX_36"
    open static let TPOSWOD_FLEX_37    = "TPOSWOD_FLEX_37"
    open static let TPOSWOD_FLEX_38    = "TPOSWOD_FLEX_38"
    open static let TPOSWOD_FLEX_39    = "TPOSWOD_FLEX_39"
    open static let TPOSWOD_FLEX_40    = "TPOSWOD_FLEX_40"
    open static let TPOSWOD_FLEX_41    = "TPOSWOD_FLEX_41"
    open static let TPOSWOD_FLEX_42    = "TPOSWOD_FLEX_42"
    open static let TPOSWOD_FLEX_43    = "TPOSWOD_FLEX_43"
    open static let TPOSWOD_FLEX_44    = "TPOSWOD_FLEX_44"
    open static let TPOSWOD_FLEX_45    = "TPOSWOD_FLEX_45"
    open static let TPOSWOD_FLEX_46    = "TPOSWOD_FLEX_46"
    open static let TPOSWOD_FLEX_47    = "TPOSWOD_FLEX_47"
    open static let TPOSWOD_FLEX_48    = "TPOSWOD_FLEX_48"
    open static let TPOSWOD_FLEX_49    = "TPOSWOD_FLEX_49"
    open static let TPOSWOD_FLEX_50    = "TPOSWOD_FLEX_50"
    open static let TPOSWOD_FLEX_51    = "TPOSWOD_FLEX_51"
    open static let TPOSWOD_FLEX_52    = "TPOSWOD_FLEX_52"
    open static let TPOSWOD_FLEX_53    = "TPOSWOD_FLEX_53"
    open static let TPOSWOD_FLEX_54    = "TPOSWOD_FLEX_54"
    open static let TPOSWOD_FLEX_55    = "TPOSWOD_FLEX_55"
    open static let TPOSWOD_FLEX_56    = "TPOSWOD_FLEX_56"
    open static let TPOSWOD_FLEX_57    = "TPOSWOD_FLEX_57"
    open static let TPOSWOD_FLEX_58    = "TPOSWOD_FLEX_58"
    open static let TPOSWOD_FLEX_59    = "TPOSWOD_FLEX_59"
    open static let TPOSWOD_FLEX_60    = "TPOSWOD_FLEX_60"
    open static let TPOSWOD_FLEX_61    = "TPOSWOD_FLEX_61"
    open static let TPOSWOD_FLEX_62    = "TPOSWOD_FLEX_62"
    open static let TPOSWOD_FLEX_63    = "TPOSWOD_FLEX_63"
    open static let TPOSWOD_FLEX_64    = "TPOSWOD_FLEX_64"
    open static let TPOSWOD_FLEX_65    = "TPOSWOD_FLEX_65"
    open static let TPOSWOD_FLEX_66    = "TPOSWOD_FLEX_66"
    open static let TPOSWOD_FLEX_67    = "TPOSWOD_FLEX_67"
    open static let TPOSWOD_FLEX_68    = "TPOSWOD_FLEX_68"
    open static let TPOSWOD_FLEX_69    = "TPOSWOD_FLEX_69"
    open static let TPOSWOD_FLEX_70    = "TPOSWOD_FLEX_70"
    open static let TPOSWOD_FLEX_71    = "TPOSWOD_FLEX_71"
    open static let TPOSWOD_FLEX_72    = "TPOSWOD_FLEX_72"
    open static let TPOSWOD_FLEX_73    = "TPOSWOD_FLEX_73"
    open static let TPOSWOD_FLEX_74    = "TPOSWOD_FLEX_74"
    open static let TPOSWOD_FLEX_75    = "TPOSWOD_FLEX_75"
    open static let TPOSWOD_FLEX_76    = "TPOSWOD_FLEX_76"
    open static let TPOSWOD_FLEX_77    = "TPOSWOD_FLEX_77"
    open static let TPOSWOD_FLEX_78    = "TPOSWOD_FLEX_78"
    open static let TPOSWOD_FLEX_79    = "TPOSWOD_FLEX_79"
    open static let TPOSWOD_FLEX_80    = "TPOSWOD_FLEX_80"
    open static let TPOSWOD_FLEX_81    = "TPOSWOD_FLEX_81"
    open static let TPOSWOD_FLEX_82    = "TPOSWOD_FLEX_82"
    open static let TPOSWOD_FLEX_83    = "TPOSWOD_FLEX_83"
    open static let TPOSWOD_FLEX_84    = "TPOSWOD_FLEX_84"
    open static let TPOSWOD_FLEX_85    = "TPOSWOD_FLEX_85"
    open static let TPOSWOD_FLEX_86    = "TPOSWOD_FLEX_86"
    open static let TPOSWOD_FLEX_87    = "TPOSWOD_FLEX_87"
    open static let TPOSWOD_FLEX_88    = "TPOSWOD_FLEX_88"
    open static let TPOSWOD_FLEX_89    = "TPOSWOD_FLEX_89"
    open static let TPOSWOD_FLEX_90    = "TPOSWOD_FLEX_90"
    open static let TPOSWOD_FLEX_91    = "TPOSWOD_FLEX_91"
    open static let TPOSWOD_FLEX_92    = "TPOSWOD_FLEX_92"
    open static let TPOSWOD_FLEX_93    = "TPOSWOD_FLEX_93"
    open static let TPOSWOD_FLEX_94    = "TPOSWOD_FLEX_94"
    open static let TPOSWOD_FLEX_95    = "TPOSWOD_FLEX_95"
    open static let TPOSWOD_FLEX_96    = "TPOSWOD_FLEX_96"
    open static let TPOSWOD_FLEX_97    = "TPOSWOD_FLEX_97"
    open static let TPOSWOD_FLEX_98    = "TPOSWOD_FLEX_98"
    open static let TPOSWOD_FLEX_99    = "TPOSWOD_FLEX_99"
    open static let TPOSWOD_FLEX_100   = "TPOSWOD_FLEX_100"
    open static let TPOSWOD_CR_UID     = "TPOSWOD_CR_UID"
    open static let TPOSWOD_CR_DT      = "TPOSWOD_CR_DT"
    open static let TPOSWOD_UPD_UID    = "TPOSWOD_UPD_UID"
    open static let TPOSWOD_UPD_DT     = "TPOSWOD_UPD_DT"
    open static let TPOSWOD_LOCN_ASSIGNED = "TPOSWOD_LOCN_ASSIGNED"
    open static let TPOSWOD_OPTIMETRIST = "TPOSWOD_OPTIMETRIST"
    open static let TPOSWOD_PRES_TYPE = "TPOSWOD_PRES_TYPE"
    open static let TPOSWOD_PRES_NUMBER = "TPOSWOD_PRES_NUMBER"
    open static let TPOSWOD_DELIVERY_DATE = "TPOSWOD_DELIVERY_DATE"
    
    open static let TPOSWOCM_SYS_ID         			= "TPOSWOCM_SYS_ID"
    open static let TPOSWOCM_CTL_PARENT       		= "TPOSWOCM_CTL_PARENT"
    open static let TPOSWOCM_CTL_GROUP          		= "TPOSWOCM_CTL_GROUP"
    open static let TPOSWOCM_CTL_GROUP_NAME           = "TPOSWOCM_CTL_GROUP_NAME"
    open static let TPOSWOCM_CTL_TYPE         		= "TPOSWOCM_CTL_TYPE"
    open static let TPOSWOCM_CTL_NAME          		= "TPOSWOCM_CTL_NAME"
    open static let TPOSWOCM_CTL_LABEL_TEXT         	= "TPOSWOCM_CTL_LABEL_TEXT"
    open static let TPOSWOCM_CTL_DATATYPE             = "TPOSWOCM_CTL_DATATYPE"
    open static let TPOSWOCM_CTL_MIN_CHAR         	= "TPOSWOCM_CTL_MIN_CHAR"
    open static let TPOSWOCM_CTL_MAX_CHAR         	= "TPOSWOCM_CTL_MAX_CHAR"
    open static let TPOSWOCM_CTL_MANDATORY          	= "TPOSWOCM_CTL_MANDATORY"
    open static let TPOSWOCM_CTL_MAPPED_FIELD         = "TPOSWOCM_CTL_MAPPED_FIELD"
    open static let TPOSWOCM_CR_UID           		= "TPOSWOCM_CR_UID"
    open static let TPOSWOCM_CR_DT            		= "TPOSWOCM_CR_DT"
    open static let TPOSWOCM_UPD_UID          		= "TPOSWOCM_UPD_UID"
    open static let TPOSWOCM_UPD_DT           		= "TPOSWOCM_UPD_DT"
    
    open static let TPOSWOCMV_SYS_ID                  = "TPOSWOCMV_SYS_ID"
    open static let TPOSWOCMV_CTL_SYS_ID              = "TPOSWOCMV_CTL_SYS_ID"
    open static let TPOSWOCMV_CTL_CODE                = "TPOSWOCMV_CTL_CODE"
    open static let TPOSWOCMV_CTL_VALUE               = "TPOSWOCMV_CTL_VALUE"
    
    open static let WO_FROM_DATE = "WO_FROM_DATE"
    open static let WO_TO_DATE = "WO_TO_DATE"
    open static let WO_LOCN_CREATED = "WO_LOCN_CREATED"
    open static let WO_CREATED_USER = "WO_CREATED_USER"
    open static let WO_STATUS = "WO_STATUS"
    open static let WO_LOCN_ASSIGNED = "WO_LOCN_ASSIGNED"
    open static let WO_PRESCRIPTION_TYPE = "WO_PRESCRIPTION_TYPE"
    
    open static let RO_FROM_DATE = "RO_FROM_DATE"
    open static let RO_TO_DATE = "RO_TO_DATE"
    open static let RO_LOCN_CREATED = "RO_LOCN_CREATED"
    open static let RO_CREATED_USER = "RO_CREATED_USER"
    open static let RO_STATUS = "RO_STATUS"
    open static let RO_LOCN_ASSIGNED = "RO_LOCN_ASSIGNED"
    
    open static let JWH_SYS_ID = "JWH_SYS_ID"
    open static let JWH_COMP_CODE = "JWH_COMP_CODE"
    open static let JWH_LOCN_CODE = "JWH_LOCN_CODE"
    open static let JWH_TXN_CODE = "JWH_TXN_CODE"
    open static let JWH_NO = "JWH_NO"
    open static let JWH_DT = "JWH_DT"
    open static let JWH_REF_SYS_ID = "JWH_REF_SYS_ID"
    open static let JWH_REF_TXN_CODE = "JWH_REF_TXN_CODE"
    open static let JWH_REF_NO = "JWH_REF_NO"
    open static let JWH_PATIENT_ID = "JWH_PATIENT_ID"
    open static let JWH_PM_SYS_ID = "JWH_PM_SYS_ID"
    open static let JWH_COMPLETED_YN = "JWH_COMPLETED_YN"
    open static let JWH_COMPLETED_UID = "JWH_COMPLETED_UID"
    open static let JWH_COMPLETED_DT = "JWH_COMPLETED_DT"
    open static let JWH_FLEX_01 = "JWH_FLEX_01"
    open static let JWH_FLEX_02 = "JWH_FLEX_02"
    open static let JWH_FLEX_03 = "JWH_FLEX_03"
    open static let JWH_FLEX_04 = "JWH_FLEX_04"
    open static let JWH_FLEX_05 = "JWH_FLEX_05"
    open static let JWH_FLEX_06 = "JWH_FLEX_06"
    open static let JWH_FLEX_07 = "JWH_FLEX_07"
    open static let JWH_FLEX_08 = "JWH_FLEX_08"
    open static let JWH_FLEX_09 = "JWH_FLEX_09"
    open static let JWH_FLEX_10 = "JWH_FLEX_10"
    open static let JWH_FLEX_11 = "JWH_FLEX_11"
    open static let JWH_FLEX_12 = "JWH_FLEX_12"
    open static let JWH_FLEX_13 = "JWH_FLEX_13"
    open static let JWH_FLEX_14 = "JWH_FLEX_14"
    open static let JWH_FLEX_15 = "JWH_FLEX_15"
    open static let JWH_FLEX_16 = "JWH_FLEX_16"
    open static let JWH_FLEX_17 = "JWH_FLEX_17"
    open static let JWH_FLEX_18 = "JWH_FLEX_18"
    open static let JWH_FLEX_19 = "JWH_FLEX_19"
    open static let JWH_FLEX_20 = "JWH_FLEX_20"
    open static let JWH_CR_UID = "JWH_CR_UID"
    open static let JWH_CR_DT = "JWH_CR_DT"
    open static let JWH_UPD_UID = "JWH_UPD_UID"
    open static let JWH_UPD_DT = "JWH_UPD_DT"
    open static let JWH_REMARKS = "JWH_REMARKS"
    
    open static let JWD_SYS_ID = "JWD_SYS_ID"
    open static let JWD_JWH_SYS_ID = "JWD_JWH_SYS_ID"
    open static let JWD_STATUS_CODE = "JWD_STATUS_CODE"
    open static let JWD_STATUS_FLAG = "JWD_STATUS_FLAG"
    open static let JWD_FLEX_01 = "JWD_FLEX_01"
    open static let JWD_FLEX_02 = "JWD_FLEX_02"
    open static let JWD_FLEX_03 = "JWD_FLEX_03"
    open static let JWD_FLEX_04 = "JWD_FLEX_04"
    open static let JWD_FLEX_05 = "JWD_FLEX_05"
    open static let JWD_FLEX_06 = "JWD_FLEX_06"
    open static let JWD_FLEX_07 = "JWD_FLEX_07"
    open static let JWD_FLEX_08 = "JWD_FLEX_08"
    open static let JWD_FLEX_09 = "JWD_FLEX_09"
    open static let JWD_FLEX_10 = "JWD_FLEX_10"
    open static let JWD_CR_UID = "JWD_CR_UID"
    open static let JWD_CR_DT = "JWD_CR_DT"
    open static let JWD_UPD_UID = "JWD_UPD_UID"
    open static let JWD_UPD_DT = "JWD_UPD_DT"
    open static let JWD_REMARKS = "JWD_REMARKS"
    
    open static let JRH_NO = "JRH_NO"
    open static let JRH_SYS_ID = "JRH_SYS_ID"
    open static let JRH_COMP_CODE = "JRH_COMP_CODE"
    open static let JRH_LOCN_CODE = "JRH_LOCN_CODE"
    open static let JRH_TXN_CODE = "JRH_TXN_CODE"
    open static let JRH_DT = "JRH_DT"
    open static let JRH_REF_SYS_ID = "JRH_REF_SYS_ID"
    open static let JRH_REF_TXN_CODE = "JRH_REF_TXN_CODE"
    open static let JRH_REF_NO = "JRH_REF_NO"
    open static let JRH_PATIENT_ID = "JRH_PATIENT_ID"
    open static let JRH_PM_SYS_ID = "JRH_PM_SYS_ID"
    open static let JRH_COMPLETED_YN = "JRH_COMPLETED_YN"
    open static let JRH_COMPLETED_UID = "JRH_COMPLETED_UID"
    open static let JRH_COMPLETED_DT = "JRH_COMPLETED_DT"
    open static let JRH_FLEX_01 = "JRH_FLEX_01"
    open static let JRH_FLEX_02 = "JRH_FLEX_02"
    open static let JRH_FLEX_03 = "JRH_FLEX_03"
    open static let JRH_FLEX_04 = "JRH_FLEX_04"
    open static let JRH_FLEX_05 = "JRH_FLEX_05"
    open static let JRH_FLEX_06 = "JRH_FLEX_06"
    open static let JRH_FLEX_07 = "JRH_FLEX_07"
    open static let JRH_FLEX_08 = "JRH_FLEX_08"
    open static let JRH_FLEX_09 = "JRH_FLEX_09"
    open static let JRH_FLEX_10 = "JRH_FLEX_10"
    open static let JRH_FLEX_11 = "JRH_FLEX_11"
    open static let JRH_FLEX_12 = "JRH_FLEX_12"
    open static let JRH_FLEX_13 = "JRH_FLEX_13"
    open static let JRH_FLEX_14 = "JRH_FLEX_14"
    open static let JRH_FLEX_15 = "JRH_FLEX_15"
    open static let JRH_FLEX_16 = "JRH_FLEX_16"
    open static let JRH_FLEX_17 = "JRH_FLEX_17"
    open static let JRH_FLEX_18 = "JRH_FLEX_18"
    open static let JRH_FLEX_19 = "JRH_FLEX_19"
    open static let JRH_FLEX_20 = "JRH_FLEX_20"
    open static let JRH_CR_UID = "JRH_CR_UID"
    open static let JRH_CR_DT  = "JRH_CR_DT"
    open static let JRH_UPD_UID = "JRH_UPD_UID"
    open static let JRH_UPD_DT = "JRH_UPD_DT"
    open static let JRH_REMARKS = "JRH_REMARKS"
    open static let JRH_ITEM_WARRANTY = "JRH_ITEM_WARRANTY"
    open static let JRH_ORIGINAL_CASE = "JRH_ORIGINAL_CASE"
    open static let JRH_INVOICE_NO = "JRH_INVOICE_NO"
    open static let JRH_INVOICE_ITEM_CODE = "JRH_INVOICE_ITEM_CODE"
    
    open static let JRD_SYS_ID = "JRD_SYS_ID"
    open static let JRD_JWH_SYS_ID = "JRD_JWH_SYS_ID"
    open static let JRD_STATUS_CODE = "JRD_STATUS_CODE"
    open static let JRD_STATUS_FLAG = "JRD_STATUS_FLAG"
    open static let JRD_FLEX_01 = "JRD_FLEX_01"
    open static let JRD_FLEX_02 = "JRD_FLEX_02"
    open static let JRD_FLEX_03 = "JRD_FLEX_03"
    open static let JRD_FLEX_04 = "JRD_FLEX_04"
    open static let JRD_FLEX_05 = "JRD_FLEX_05"
    open static let JRD_FLEX_06 = "JRD_FLEX_06"
    open static let JRD_FLEX_07 = "JRD_FLEX_07"
    open static let JRD_FLEX_08 = "JRD_FLEX_08"
    open static let JRD_FLEX_09 = "JRD_FLEX_09"
    open static let JRD_FLEX_10 = "JRD_FLEX_10"
    open static let JRD_CR_UID  = "JRD_CR_UID"
    open static let JRD_CR_DT   = "JRD_CR_DT"
    open static let JRD_UPD_UID = "JRD_UPD_UID"
    open static let JRD_UPD_DT  = "JRD_UPD_DT"
    open static let JRD_REMARKS = "JRD_REMARKS"
    
    open static let TPOSROD_SYS_ID   = "TPOSROD_SYS_ID"
    open static let TPOSROD_HEAD_SYS_ID   = "TPOSROD_HEAD_SYS_ID"
    open static let TPOSROD_FLEX_1  =  "TPOSROD_FLEX_1"
    open static let TPOSROD_FLEX_2  =  "TPOSROD_FLEX_2"
    open static let TPOSROD_FLEX_3  =  "TPOSROD_FLEX_3"
    open static let TPOSROD_FLEX_4  =  "TPOSROD_FLEX_4"
    open static let TPOSROD_FLEX_5  =  "TPOSROD_FLEX_5"
    open static let TPOSROD_FLEX_6  =  "TPOSROD_FLEX_6"
    open static let TPOSROD_FLEX_7  =  "TPOSROD_FLEX_7"
    open static let TPOSROD_FLEX_8  =  "TPOSROD_FLEX_8"
    open static let TPOSROD_FLEX_9  =  "TPOSROD_FLEX_9"
    open static let TPOSROD_FLEX_10 =  "TPOSROD_FLEX_10"
    open static let TPOSROD_FLEX_11 =  "TPOSROD_FLEX_11"
    open static let TPOSROD_FLEX_12 =  "TPOSROD_FLEX_12"
    open static let TPOSROD_FLEX_13 =  "TPOSROD_FLEX_13"
    open static let TPOSROD_FLEX_14 =  "TPOSROD_FLEX_14"
    open static let TPOSROD_FLEX_15 =  "TPOSROD_FLEX_15"
    open static let TPOSROD_FLEX_16 =  "TPOSROD_FLEX_16"
    open static let TPOSROD_FLEX_17 =  "TPOSROD_FLEX_17"
    open static let TPOSROD_FLEX_18 =  "TPOSROD_FLEX_18"
    open static let TPOSROD_FLEX_19 =  "TPOSROD_FLEX_19"
    open static let TPOSROD_FLEX_20 =  "TPOSROD_FLEX_20"
    open static let TPOSROD_FLEX_21 =  "TPOSROD_FLEX_21"
    open static let TPOSROD_FLEX_22 =  "TPOSROD_FLEX_22"
    open static let TPOSROD_FLEX_23 =  "TPOSROD_FLEX_23"
    open static let TPOSROD_FLEX_24 =  "TPOSROD_FLEX_24"
    open static let TPOSROD_FLEX_25 =  "TPOSROD_FLEX_25"
    open static let TPOSROD_FLEX_26 =  "TPOSROD_FLEX_26"
    open static let TPOSROD_FLEX_27 =  "TPOSROD_FLEX_27"
    open static let TPOSROD_FLEX_28 =  "TPOSROD_FLEX_28"
    open static let TPOSROD_FLEX_29 =  "TPOSROD_FLEX_29"
    open static let TPOSROD_FLEX_30 =  "TPOSROD_FLEX_30"
    open static let TPOSROD_FLEX_31 =  "TPOSROD_FLEX_31"
    open static let TPOSROD_FLEX_32 =  "TPOSROD_FLEX_32"
    open static let TPOSROD_FLEX_33 =  "TPOSROD_FLEX_33"
    open static let TPOSROD_FLEX_34 =  "TPOSROD_FLEX_34"
    open static let TPOSROD_FLEX_35 =  "TPOSROD_FLEX_35"
    open static let TPOSROD_FLEX_36 =  "TPOSROD_FLEX_36"
    open static let TPOSROD_FLEX_37 =  "TPOSROD_FLEX_37"
    open static let TPOSROD_FLEX_38 =  "TPOSROD_FLEX_38"
    open static let TPOSROD_FLEX_39 =  "TPOSROD_FLEX_39"
    open static let TPOSROD_FLEX_40 =  "TPOSROD_FLEX_40"
    open static let TPOSROD_FLEX_41 =  "TPOSROD_FLEX_41"
    open static let TPOSROD_FLEX_42 =  "TPOSROD_FLEX_42"
    open static let TPOSROD_FLEX_43 =  "TPOSROD_FLEX_43"
    open static let TPOSROD_FLEX_44 =  "TPOSROD_FLEX_44"
    open static let TPOSROD_FLEX_45 =  "TPOSROD_FLEX_45"
    open static let TPOSROD_FLEX_46 =  "TPOSROD_FLEX_46"
    open static let TPOSROD_FLEX_47 =  "TPOSROD_FLEX_47"
    open static let TPOSROD_FLEX_48 =  "TPOSROD_FLEX_48"
    open static let TPOSROD_FLEX_49 =  "TPOSROD_FLEX_49"
    open static let TPOSROD_FLEX_50 =  "TPOSROD_FLEX_50"
    open static let TPOSROD_FLEX_51 =  "TPOSROD_FLEX_51"
    open static let TPOSROD_FLEX_52 =  "TPOSROD_FLEX_52"
    open static let TPOSROD_FLEX_53 =  "TPOSROD_FLEX_53"
    open static let TPOSROD_FLEX_54 =  "TPOSROD_FLEX_54"
    open static let TPOSROD_FLEX_55 =  "TPOSROD_FLEX_55"
    open static let TPOSROD_FLEX_56 =  "TPOSROD_FLEX_56"
    open static let TPOSROD_FLEX_57 =  "TPOSROD_FLEX_57"
    open static let TPOSROD_FLEX_58 =  "TPOSROD_FLEX_58"
    open static let TPOSROD_FLEX_59 =  "TPOSROD_FLEX_59"
    open static let TPOSROD_FLEX_60 =  "TPOSROD_FLEX_60"
    open static let TPOSROD_FLEX_61 =  "TPOSROD_FLEX_61"
    open static let TPOSROD_FLEX_62 =  "TPOSROD_FLEX_62"
    open static let TPOSROD_FLEX_63 =  "TPOSROD_FLEX_63"
    open static let TPOSROD_FLEX_64 =  "TPOSROD_FLEX_64"
    open static let TPOSROD_FLEX_65 =  "TPOSROD_FLEX_65"
    open static let TPOSROD_FLEX_66 =  "TPOSROD_FLEX_66"
    open static let TPOSROD_FLEX_67 =  "TPOSROD_FLEX_67"
    open static let TPOSROD_FLEX_68 =  "TPOSROD_FLEX_68"
    open static let TPOSROD_FLEX_69 =  "TPOSROD_FLEX_69"
    open static let TPOSROD_FLEX_70 =  "TPOSROD_FLEX_70"
    open static let TPOSROD_FLEX_71 =  "TPOSROD_FLEX_71"
    open static let TPOSROD_FLEX_72 =  "TPOSROD_FLEX_72"
    open static let TPOSROD_FLEX_73 =  "TPOSROD_FLEX_73"
    open static let TPOSROD_FLEX_74 =  "TPOSROD_FLEX_74"
    open static let TPOSROD_FLEX_75 =  "TPOSROD_FLEX_75"
    open static let TPOSROD_FLEX_76 =  "TPOSROD_FLEX_76"
    open static let TPOSROD_FLEX_77 =  "TPOSROD_FLEX_77"
    open static let TPOSROD_FLEX_78 =  "TPOSROD_FLEX_78"
    open static let TPOSROD_FLEX_79 =  "TPOSROD_FLEX_79"
    open static let TPOSROD_FLEX_80 =  "TPOSROD_FLEX_80"
    open static let TPOSROD_FLEX_81 =  "TPOSROD_FLEX_81"
    open static let TPOSROD_FLEX_82 =  "TPOSROD_FLEX_82"
    open static let TPOSROD_FLEX_83 =  "TPOSROD_FLEX_83"
    open static let TPOSROD_FLEX_84 =  "TPOSROD_FLEX_84"
    open static let TPOSROD_FLEX_85 =  "TPOSROD_FLEX_85"
    open static let TPOSROD_FLEX_86 =  "TPOSROD_FLEX_86"
    open static let TPOSROD_FLEX_87 =  "TPOSROD_FLEX_87"
    open static let TPOSROD_FLEX_88 =  "TPOSROD_FLEX_88"
    open static let TPOSROD_FLEX_89 =  "TPOSROD_FLEX_89"
    open static let TPOSROD_FLEX_90 =  "TPOSROD_FLEX_90"
    open static let TPOSROD_FLEX_91 =  "TPOSROD_FLEX_91"
    open static let TPOSROD_FLEX_92 =  "TPOSROD_FLEX_92"
    open static let TPOSROD_FLEX_93 =  "TPOSROD_FLEX_93"
    open static let TPOSROD_FLEX_94 =  "TPOSROD_FLEX_94"
    open static let TPOSROD_FLEX_95 =  "TPOSROD_FLEX_95"
    open static let TPOSROD_FLEX_96 =  "TPOSROD_FLEX_96"
    open static let TPOSROD_FLEX_97 =  "TPOSROD_FLEX_97"
    open static let TPOSROD_FLEX_98 =  "TPOSROD_FLEX_98"
    open static let TPOSROD_FLEX_99 =  "TPOSROD_FLEX_99"
    open static let TPOSROD_FLEX_100 = "TPOSROD_FLEX_100"
    open static let TPOSROD_FLEX_101 = "TPOSROD_FLEX_101"
    open static let TPOSROD_FLEX_102 = "TPOSROD_FLEX_102"
    open static let TPOSROD_FLEX_103 = "TPOSROD_FLEX_103"
    open static let TPOSROD_FLEX_104 = "TPOSROD_FLEX_104"
    open static let TPOSROD_FLEX_105 = "TPOSROD_FLEX_105"
    open static let TPOSROD_FLEX_106 = "TPOSROD_FLEX_106"
    open static let TPOSROD_FLEX_107 = "TPOSROD_FLEX_107"
    open static let TPOSROD_FLEX_108 = "TPOSROD_FLEX_108"
    open static let TPOSROD_FLEX_109 = "TPOSROD_FLEX_109"
    open static let TPOSROD_FLEX_110 = "TPOSROD_FLEX_110"
    open static let TPOSROD_FLEX_111 = "TPOSROD_FLEX_111"
    open static let TPOSROD_FLEX_112 = "TPOSROD_FLEX_112"
    open static let TPOSROD_FLEX_113 = "TPOSROD_FLEX_113"
    open static let TPOSROD_FLEX_114 = "TPOSROD_FLEX_114"
    open static let TPOSROD_FLEX_115 = "TPOSROD_FLEX_115"
    open static let TPOSROD_FLEX_116 = "TPOSROD_FLEX_116"
    open static let TPOSROD_FLEX_117 = "TPOSROD_FLEX_117"
    open static let TPOSROD_FLEX_118 = "TPOSROD_FLEX_118"
    open static let TPOSROD_FLEX_119 = "TPOSROD_FLEX_119"
    open static let TPOSROD_FLEX_120 = "TPOSROD_FLEX_120"
    open static let TPOSROD_FLEX_121 = "TPOSROD_FLEX_121"
    open static let TPOSROD_FLEX_122 = "TPOSROD_FLEX_122"
    open static let TPOSROD_FLEX_123 = "TPOSROD_FLEX_123"
    open static let TPOSROD_FLEX_124 = "TPOSROD_FLEX_124"
    /*open static let TPOSROD_FLEX_125
     open static let TPOSROD_FLEX_126
     open static let TPOSROD_FLEX_127
     open static let TPOSROD_FLEX_128
     open static let TPOSROD_FLEX_129
     open static let TPOSROD_FLEX_130
     open static let TPOSROD_FLEX_131
     open static let TPOSROD_FLEX_132
     open static let TPOSROD_FLEX_133
     open static let TPOSROD_FLEX_134
     open static let TPOSROD_FLEX_135
     open static let TPOSROD_FLEX_136
     open static let TPOSROD_FLEX_137
     open static let TPOSROD_FLEX_138
     open static let TPOSROD_FLEX_139
     open static let TPOSROD_FLEX_140
     open static let TPOSROD_FLEX_141
     open static let TPOSROD_FLEX_142
     open static let TPOSROD_FLEX_143
     open static let TPOSROD_FLEX_144
     open static let TPOSROD_FLEX_145
     open static let TPOSROD_FLEX_146
     open static let TPOSROD_FLEX_147
     open static let TPOSROD_FLEX_148
     open static let TPOSROD_FLEX_149
     open static let TPOSROD_FLEX_150
     open static let TPOSROD_FLEX_151
     open static let TPOSROD_FLEX_152
     open static let TPOSROD_FLEX_153
     open static let TPOSROD_FLEX_154
     open static let TPOSROD_FLEX_155
     open static let TPOSROD_FLEX_156
     open static let TPOSROD_FLEX_157
     open static let TPOSROD_FLEX_158
     open static let TPOSROD_FLEX_159
     open static let TPOSROD_FLEX_160
     open static let TPOSROD_FLEX_161
     open static let TPOSROD_FLEX_162
     open static let TPOSROD_FLEX_163
     open static let TPOSROD_FLEX_164
     open static let TPOSROD_FLEX_165
     open static let TPOSROD_FLEX_166
     open static let TPOSROD_FLEX_167
     open static let TPOSROD_FLEX_168
     open static let TPOSROD_FLEX_169
     open static let TPOSROD_FLEX_170
     open static let TPOSROD_FLEX_171
     open static let TPOSROD_FLEX_172
     open static let TPOSROD_FLEX_173
     open static let TPOSROD_FLEX_174
     open static let TPOSROD_FLEX_175
     open static let TPOSROD_FLEX_176
     open static let TPOSROD_FLEX_177
     open static let TPOSROD_FLEX_178
     open static let TPOSROD_FLEX_179
     open static let TPOSROD_FLEX_180
     open static let TPOSROD_FLEX_181
     open static let TPOSROD_FLEX_182
     open static let TPOSROD_FLEX_183
     open static let TPOSROD_FLEX_184
     open static let TPOSROD_FLEX_185
     open static let TPOSROD_FLEX_186
     open static let TPOSROD_FLEX_187
     open static let TPOSROD_FLEX_188
     open static let TPOSROD_FLEX_189
     open static let TPOSROD_FLEX_190
     open static let TPOSROD_FLEX_191
     open static let TPOSROD_FLEX_192
     open static let TPOSROD_FLEX_193
     open static let TPOSROD_FLEX_194
     open static let TPOSROD_FLEX_195
     open static let TPOSROD_FLEX_196
     open static let TPOSROD_FLEX_197
     open static let TPOSROD_FLEX_198
     open static let TPOSROD_FLEX_199
     open static let TPOSROD_FLEX_200  */
    open static let TPOSROD_CR_UID = "TPOSROD_CR_UID"
    open static let TPOSROD_CR_DT  = "TPOSROD_CR_DT"
    open static let TPOSROD_UPD_UID = "TPOSROD_UPD_UID"
    open static let TPOSROD_UPD_DT = "TPOSROD_UPD_DT"
    open static let TPOSROD_LOCN_ASSIGNED = "TPOSROD_LOCN_ASSIGNED"
    open static let TPOSROD_OPTIMETRIST = "TPOSROD_OPTIMETRIST"
    open static let TPOSROD_DELIVERY_DATE = "TPOSROD_DELIVERY_DATE"
    
}
